name: test-linux

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:


jobs:
  imager-zxing:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        release:
          - version: "default"
          - version: "2.1.0"
            cmake-options: 
          - version: "2.2.0"
            cmake-options: 
          - version: "2.3.0"
            cmake-options:
    steps:
      - name: install dependencies
        run: |
            apt update ||:
            apt -y install build-essential libextutils-cppguess-perl libtest-pod-perl wget pkgconf cmake git
            if [ "${{ matrix.release.version }}" = "default" ]; then
              apt -y install libzxing-dev
            else
              wget https://github.com/zxing-cpp/zxing-cpp/archive/refs/tags/v${{ matrix.release.version }}.tar.gz
              ls
              tar xzf v${{ matrix.release.version }}.tar.gz
              ls
              cd zxing-cpp-${{ matrix.release.version }}
              mkdir build
              cmake -B build ${{ matrix.release.cmake-options }} && cd build && make && make install
              echo "LD_LIBRARY_PATH=$(pkg-config --variable=libdir zxing)" >>$GITHUB_ENV
            fi
            cpan Imager
      - name: checkout
        uses: actions/checkout@v2
      - name: configure
        run: |
          perl Makefile.PL
      - name: build
        run: |
            make -j2
      - name: test
        run: |
            make test
