name: test-linux

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:


jobs:
  imager-zxing:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ZXING_RELEASE:
          - "2.1.0"
          - "2.2.0"
          - "2.3.0"
    steps:
      - name: install dependencies
        run: |
            sudo apt-get update ||:
            sudo apt-get -y install build-essential libextutils-cppguess-perl libtest-pod-perl
            wget https://github.com/zxing-cpp/zxing-cpp/archive/refs/tags/v${{matrix/ZXING_RELEASE }}.tar.gz
            ls
            tar xzf v${{ matrix.ZXING_RELEASE}.tar.gz
            ls
            cd zxing-cpp-${{ matrix.ZXING_RELEASE }}
            mkdir build
            cmake -B build && cd build && make && sudo make install
            echo "LD_LIBRARY_PATH=$(pkg-config --variable=libdir zxing)" >>$GITHUB_ENV
            sudo cpan Imager
      - name: checkout
        uses: actions/checkout@v2
      - name: configure
        run: |
          perl Makefile.PL
      - name: build
        run: |
            make -j2
      - name: test
        run: |
            make test
