name: test-linux

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:


jobs:
  imager:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: install dependencies
        run: |
            sudo apt-get update ||:
            sudo apt-get -y install build-essential libimager-perl libextutils-cppguess-perl
      - name: checkout
        uses: actions/checkout@v2
      - name: configure
        run: |
          perl Makefile.PL
      - name: build
        run: |
            make -j2
      - name: test
        run: |
            make test
